import type { Schema } from "../api/types";
// Demo-only PDF writer. Production reports are generated by the backend.
// JPEG pages avoid substituting Cyrillic fonts in browser-generated fixtures.
export function pdfFromJpegs(
  pages: Uint8Array[],
  width: number,
  height: number,
): Uint8Array {
  const encoder = new TextEncoder();
  const chunks: Uint8Array[] = [];
  let length = 0;
  const add = (v: string | Uint8Array) => {
    const bytes = typeof v === "string" ? encoder.encode(v) : v;
    chunks.push(bytes);
    length += bytes.length;
  };
  const offsets = [0];
  const object = (id: number, body: string) => {
    offsets[id] = length;
    add(`${id} 0 obj\n${body}\nendobj\n`);
  };
  add("%PDF-1.4\n");
  object(1, "<< /Type /Catalog /Pages 2 0 R >>");
  object(
    2,
    `<< /Type /Pages /Count ${pages.length} /Kids [${pages.map((_, i) => `${3 + i * 3} 0 R`).join(" ")}] >>`,
  );
  pages.forEach((jpg, i) => {
    const id = 3 + i * 3;
    object(
      id,
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im${i} ${id + 1} 0 R >> >> /Contents ${id + 2} 0 R >>`,
    );
    offsets[id + 1] = length;
    add(
      `${id + 1} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpg.length} >>\nstream\n`,
    );
    add(jpg);
    add("\nendstream\nendobj\n");
    const content = `q 595 0 0 842 0 0 cm /Im${i} Do Q\n`;
    object(
      id + 2,
      `<< /Length ${encoder.encode(content).length} >>\nstream\n${content}endstream`,
    );
  });
  const xref = length;
  add(`xref\n0 ${offsets.length}\n0000000000 65535 f \n`);
  offsets
    .slice(1)
    .forEach((offset) => add(`${String(offset).padStart(10, "0")} 00000 n \n`));
  add(
    `trailer\n<< /Size ${offsets.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`,
  );
  const result = new Uint8Array(length);
  let at = 0;
  for (const c of chunks) {
    result.set(c, at);
    at += c.length;
  }
  return result;
}
export async function mockStatsReport(
  charts: Schema["ChartOut"][],
  group: string,
) {
  const pages: Uint8Array[] = [];
  const width = 1190,
    height = 1684;
  for (const [page, chart] of charts.entries()) {
    const canvas = document.createElement("canvas");
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext("2d");
    if (!ctx) throw Error("Не удалось сформировать демоотчёт");
    ctx.fillStyle = "#fff";
    ctx.fillRect(0, 0, width, height);
    ctx.fillStyle = "#7700ff";
    ctx.fillRect(0, 0, width, 14);
    ctx.fillStyle = "#757b8c";
    ctx.font = "20px sans-serif";
    ctx.fillText("РАДАР ВУЗОВ / АНАЛИТИКА ПРОЦЕССОВ", 64, 85);
    ctx.fillStyle = "#171e2e";
    ctx.font = "bold 38px sans-serif";
    ctx.fillText(chart.title, 64, 166, 1060);
    ctx.font = "22px sans-serif";
    ctx.fillText(group, 64, 217, 1060);
    ctx.fillStyle = "#757b8c";
    ctx.font = "18px sans-serif";
    ctx.fillText(
      "Демонстрационные данные · " + new Date().toLocaleDateString("ru-RU"),
      64,
      255,
    );
    ctx.fillText(
      page === 1
        ? "Среднее по завершённым посещениям этапа, в днях."
        : "Количество взаимодействий в текущем срезе.",
      64,
      308,
    );
    const max = Math.max(1, ...chart.values);
    const row = Math.min(65, 1020 / Math.max(1, chart.labels.length));
    if (!chart.labels.length)
      ctx.fillText("Нет завершённых этапов для расчёта.", 64, 420);
    chart.labels.forEach((label, i) => {
      const y = 385 + i * row;
      ctx.fillStyle = "#171e2e";
      ctx.font = "18px sans-serif";
      ctx.fillText(label, 64, y, 450);
      ctx.fillStyle = "#efedf4";
      ctx.fillRect(540, y - 16, 490, 20);
      ctx.fillStyle = page === 1 ? "#ff4f12" : "#7700ff";
      ctx.fillRect(540, y - 16, (490 * (chart.values[i] || 0)) / max, 20);
      ctx.fillStyle = "#171e2e";
      ctx.fillText(String(chart.values[i] || 0), 1050, y);
    });
    ctx.fillStyle = "#757b8c";
    ctx.font = "17px sans-serif";
    ctx.fillText(
      "Синтетический отчёт деморежима. Права доступа и выбранная группа учтены.",
      64,
      1560,
    );
    ctx.fillText(`Радар вузов · ${page + 1} / ${charts.length}`, 64, 1610);
    const blob = await new Promise<Blob>((resolve, reject) =>
      canvas.toBlob(
        (b) => (b ? resolve(b) : reject(Error())),
        "image/jpeg",
        0.92,
      ),
    );
    pages.push(new Uint8Array(await blob.arrayBuffer()));
  }
  return pdfFromJpegs(pages, width, height);
}
