"""integrations

Revision ID: f655a5308c2b
Revises: 5965b66cc7ec
Create Date: 2026-09-16 21:39:20.498874+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f655a5308c2b"
down_revision: str | Sequence[str] | None = "5965b66cc7ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_source",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("base_url", sa.String(length=300), nullable=False),
        sa.Column("secret_ref", sa.String(length=120), nullable=True),
        sa.Column("is_mock", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("schedule_cron", sa.String(length=60), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('lms', 'site')", name=op.f("ck_integration_source_kind")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_source")),
        sa.UniqueConstraint("name", name=op.f("uq_integration_source_name")),
    )
    op.create_table(
        "sync_run",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.String(length=40), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('running', 'done', 'failed')", name=op.f("ck_sync_run_status")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_source.id"],
            name=op.f("fk_sync_run_source_id_integration_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_run")),
    )
    op.create_index(op.f("ix_sync_run_source_id"), "sync_run", ["source_id"], unique=False)
    op.create_table(
        "site_application",
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=True),
        sa.Column("program_id", sa.Uuid(), nullable=True),
        sa.Column("university_name", sa.String(length=300), nullable=False),
        sa.Column("program_name", sa.String(length=300), nullable=False),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("match_status", sa.String(length=16), nullable=False),
        sa.Column("interaction_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_status IN ('matched', 'unmatched')",
            name=op.f("ck_site_application_match_status"),
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interaction.id"],
            name=op.f("fk_site_application_interaction_id_interaction"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
            name=op.f("fk_site_application_program_id_program"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["university.id"],
            name=op.f("fk_site_application_university_id_university"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_application")),
        sa.UniqueConstraint("external_id", name=op.f("uq_site_application_external_id")),
    )
    op.create_index(
        op.f("ix_site_application_university_id"),
        "site_application",
        ["university_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_site_application_university_id"), table_name="site_application")
    op.drop_table("site_application")
    op.drop_index(op.f("ix_sync_run_source_id"), table_name="sync_run")
    op.drop_table("sync_run")
    op.drop_table("integration_source")
    # ### end Alembic commands ###
