"""metric source in key

Revision ID: 8fdb850e12c1
Revises: f655a5308c2b
Create Date: 2026-09-16 21:42:58.041590+00:00
"""

from collections.abc import Sequence

from alembic import op

revision: str = "8fdb850e12c1"
down_revision: str | Sequence[str] | None = "f655a5308c2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_program_metric_university_id_program_id_period_month_metric"),
        "program_metric",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_program_metric_university_id_program_id_period_month_metric_source"),
        "program_metric",
        ["university_id", "program_id", "period_month", "metric", "source"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_program_metric_university_id_program_id_period_month_metric_source"),
        "program_metric",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_program_metric_university_id_program_id_period_month_metric"),
        "program_metric",
        ["university_id", "program_id", "period_month", "metric"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
