"""import tables

Revision ID: e483bdb1e4c5
Revises: 6119d5bf3071
Create Date: 2026-09-16 14:19:16.879568+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e483bdb1e4c5"
down_revision: str | Sequence[str] | None = "6119d5bf3071"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_profile",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("file_kind", sa.String(length=8), nullable=False),
        sa.Column("column_map", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "file_kind IN ('xls', 'xlsx')", name=op.f("ck_import_profile_file_kind")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_profile")),
        sa.UniqueConstraint("name", name=op.f("uq_import_profile_name")),
    )
    op.create_table(
        "import_batch",
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_kind", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("column_map", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('uploaded', 'previewed', 'applied', 'failed')",
            name=op.f("ck_import_batch_status"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["import_profile.id"],
            name=op.f("fk_import_batch_profile_id_import_profile"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["app_user.id"],
            name=op.f("fk_import_batch_uploaded_by_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batch")),
    )
    op.create_table(
        "import_row",
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("row_no", sa.Integer(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolution", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "resolution IN ('new', 'update', 'conflict', 'skip', 'needs_program')",
            name=op.f("ck_import_row_resolution"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batch.id"],
            name=op.f("fk_import_row_batch_id_import_batch"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_row")),
    )
    op.create_index(op.f("ix_import_row_batch_id"), "import_row", ["batch_id"], unique=False)
    op.create_index("uq_import_row_batch_row_no", "import_row", ["batch_id", "row_no"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_import_row_batch_row_no", table_name="import_row")
    op.drop_index(op.f("ix_import_row_batch_id"), table_name="import_row")
    op.drop_table("import_row")
    op.drop_table("import_batch")
    op.drop_table("import_profile")
    # ### end Alembic commands ###
