"""access rules, settings, archiving

Revision ID: 3003b18b0343
Revises: 6698165c5f2b
Create Date: 2026-09-16 22:00:27.877695+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3003b18b0343"
down_revision: str | Sequence[str] | None = "6698165c5f2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_setting",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["app_user.id"],
            name=op.f("fk_app_setting_updated_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_setting")),
    )
    op.create_table(
        "data_access_rule",
        sa.Column("subject_user_id", sa.Uuid(), nullable=True),
        sa.Column("subject_role", sa.String(length=16), nullable=True),
        sa.Column("effect", sa.String(length=8), nullable=False),
        sa.Column("scope_kind", sa.String(length=16), nullable=False),
        sa.Column("scope_id", sa.Uuid(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("effect IN ('allow', 'deny')", name=op.f("ck_data_access_rule_effect")),
        sa.CheckConstraint(
            "scope_kind IN ('university', 'direction', 'program')",
            name=op.f("ck_data_access_rule_scope_kind"),
        ),
        sa.CheckConstraint(
            "(subject_user_id IS NULL) <> (subject_role IS NULL)",
            name=op.f("ck_data_access_rule_subject_exactly_one"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_user_id"],
            ["app_user.id"],
            name=op.f("fk_data_access_rule_subject_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_access_rule")),
    )
    op.create_index(
        op.f("ix_data_access_rule_subject_user_id"),
        "data_access_rule",
        ["subject_user_id"],
        unique=False,
    )
    op.add_column(
        "contact_person", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("direction", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("product", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("program", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("vendor", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendor", "archived_at")
    op.drop_column("program", "archived_at")
    op.drop_column("product", "archived_at")
    op.drop_column("direction", "archived_at")
    op.drop_column("contact_person", "archived_at")
    op.drop_index(op.f("ix_data_access_rule_subject_user_id"), table_name="data_access_rule")
    op.drop_table("data_access_rule")
    op.drop_table("app_setting")
    # ### end Alembic commands ###
