"""rating weights

Revision ID: 6698165c5f2b
Revises: 8fdb850e12c1
Create Date: 2026-09-16 21:48:47.332774+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6698165c5f2b"
down_revision: str | Sequence[str] | None = "8fdb850e12c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rating_weight_set",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("w_applications", sa.Integer(), server_default=sa.text("40"), nullable=False),
        sa.Column("w_students", sa.Integer(), server_default=sa.text("40"), nullable=False),
        sa.Column("w_streams", sa.Integer(), server_default=sa.text("20"), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "w_applications + w_students + w_streams = 100",
            name=op.f("ck_rating_weight_set_weights_sum_to_hundred"),
        ),
        sa.CheckConstraint(
            "w_applications >= 0 AND w_students >= 0 AND w_streams >= 0",
            name=op.f("ck_rating_weight_set_weights_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rating_weight_set")),
        sa.UniqueConstraint("name", name=op.f("uq_rating_weight_set_name")),
    )
    op.create_index(
        "uq_rating_weight_set_default",
        "rating_weight_set",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_rating_weight_set_default",
        table_name="rating_weight_set",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_table("rating_weight_set")
    # ### end Alembic commands ###
