"""initial schema

Revision ID: 6119d5bf3071
Revises:
Create Date: 2026-09-15 20:23:11.979391+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6119d5bf3071"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_kind", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_occurred_at"), "audit_log", ["occurred_at"], unique=False)
    op.create_table(
        "direction",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_direction")),
        sa.UniqueConstraint("code", name=op.f("uq_direction_code")),
    )
    op.create_table(
        "team",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("manager_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team")),
        sa.UniqueConstraint("name", name=op.f("uq_team_name")),
    )
    op.create_table(
        "university",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("short_name", sa.String(length=60), nullable=False),
        sa.Column("region", sa.String(length=120), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("is_priority2030", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_university")),
        sa.UniqueConstraint("name", name=op.f("uq_university_name")),
    )
    op.create_table(
        "vendor",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor")),
        sa.UniqueConstraint("name", name=op.f("uq_vendor_name")),
    )
    op.create_table(
        "workflow_template",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_template")),
        sa.UniqueConstraint("name", name=op.f("uq_workflow_template_name")),
    )
    op.create_table(
        "app_user",
        sa.Column("keycloak_sub", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('kam', 'manager', 'admin')", name=op.f("ck_app_user_role")),
        sa.ForeignKeyConstraint(
            ["team_id"], ["team.id"], name=op.f("fk_app_user_team_id_team"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
        sa.UniqueConstraint("keycloak_sub", name=op.f("uq_app_user_keycloak_sub")),
    )
    op.create_index(op.f("ix_app_user_team_id"), "app_user", ["team_id"], unique=False)
    # Циклическая связь team ↔ app_user: ключ создаётся после обеих таблиц.
    op.create_foreign_key(
        op.f("fk_team_manager_user_id_app_user"),
        "team",
        "app_user",
        ["manager_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "contact_person",
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("position", sa.String(length=200), nullable=True),
        sa.Column("email_enc", sa.LargeBinary(), nullable=True),
        sa.Column("phone_enc", sa.LargeBinary(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["university.id"],
            name=op.f("fk_contact_person_university_id_university"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_person")),
    )
    op.create_index(
        op.f("ix_contact_person_university_id"), "contact_person", ["university_id"], unique=False
    )
    op.create_table(
        "contract",
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=60), nullable=False),
        sa.Column("signed_at", sa.Date(), nullable=True),
        sa.Column("license_signed_at", sa.Date(), nullable=True),
        sa.Column("license_valid_until", sa.Date(), nullable=True),
        sa.Column("license_term_years", sa.Integer(), nullable=True),
        sa.Column("transfer_status", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["university.id"],
            name=op.f("fk_contract_university_id_university"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract")),
        sa.UniqueConstraint(
            "university_id", "number", name=op.f("uq_contract_university_id_number")
        ),
    )
    op.create_index(op.f("ix_contract_university_id"), "contract", ["university_id"], unique=False)
    op.create_table(
        "product",
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
            name=op.f("fk_product_vendor_id_vendor"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint("vendor_id", "name", name=op.f("uq_product_vendor_id_name")),
    )
    op.create_index(op.f("ix_product_vendor_id"), "product", ["vendor_id"], unique=False)
    op.create_table(
        "program",
        sa.Column("direction_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("lms_course_ref", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["direction_id"],
            ["direction.id"],
            name=op.f("fk_program_direction_id_direction"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program")),
        sa.UniqueConstraint("direction_id", "name", name=op.f("uq_program_direction_id_name")),
    )
    op.create_index(op.f("ix_program_direction_id"), "program", ["direction_id"], unique=False)
    op.create_table(
        "stage_norm",
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("stage_code", sa.String(length=60), nullable=False),
        sa.Column("norm_days", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("suggested_median_days", sa.Integer(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source IN ('manual', 'suggested')", name=op.f("ck_stage_norm_source")),
        sa.CheckConstraint("norm_days > 0", name=op.f("ck_stage_norm_norm_days_positive")),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["workflow_template.id"],
            name=op.f("fk_stage_norm_template_id_workflow_template"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_norm")),
        sa.UniqueConstraint(
            "template_id", "stage_code", name=op.f("uq_stage_norm_template_id_stage_code")
        ),
    )
    op.create_table(
        "workflow_version",
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'retired')", name=op.f("ck_workflow_version_status")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["workflow_template.id"],
            name=op.f("fk_workflow_version_template_id_workflow_template"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_version")),
        sa.UniqueConstraint(
            "template_id", "version_no", name=op.f("uq_workflow_version_template_id_version_no")
        ),
    )
    op.create_index(
        op.f("ix_workflow_version_template_id"), "workflow_version", ["template_id"], unique=False
    )
    op.create_table(
        "product_direction",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("direction_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["direction_id"],
            ["direction.id"],
            name=op.f("fk_product_direction_direction_id_direction"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_product_direction_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("product_id", "direction_id", name=op.f("pk_product_direction")),
    )
    op.create_table(
        "program_product",
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_program_product_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
            name=op.f("fk_program_product_program_id_program"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("program_id", "product_id", name=op.f("pk_program_product")),
    )
    op.create_table(
        "stage",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("bulk_allowed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "required_document_types",
            sa.ARRAY(sa.String(length=60)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('start', 'normal', 'final')", name=op.f("ck_stage_kind")),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["workflow_version.id"],
            name=op.f("fk_stage_version_id_workflow_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage")),
        sa.UniqueConstraint("version_id", "code", name=op.f("uq_stage_version_id_code")),
        sa.UniqueConstraint("version_id", "position", name=op.f("uq_stage_version_id_position")),
    )
    op.create_index(op.f("ix_stage_version_id"), "stage", ["version_id"], unique=False)
    op.create_table(
        "interaction",
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=True),
        sa.Column("workflow_version_id", sa.Uuid(), nullable=False),
        sa.Column("current_stage_id", sa.Uuid(), nullable=False),
        sa.Column("stage_entered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'import', 'site', 'lms', 'demo')",
            name=op.f("ck_interaction_source"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'completed', 'cancelled')",
            name=op.f("ck_interaction_status"),
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contract.id"],
            name=op.f("fk_interaction_contract_id_contract"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["current_stage_id"],
            ["stage.id"],
            name=op.f("fk_interaction_current_stage_id_stage"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["app_user.id"],
            name=op.f("fk_interaction_owner_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_interaction_product_id_product"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
            name=op.f("fk_interaction_program_id_program"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["university.id"],
            name=op.f("fk_interaction_university_id_university"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_version.id"],
            name=op.f("fk_interaction_workflow_version_id_workflow_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction")),
    )
    op.create_index(
        "ix_interaction_owner_status", "interaction", ["owner_user_id", "status"], unique=False
    )
    op.create_index(op.f("ix_interaction_product_id"), "interaction", ["product_id"], unique=False)
    op.create_index(op.f("ix_interaction_program_id"), "interaction", ["program_id"], unique=False)
    op.create_index(
        "ix_interaction_stage_entered",
        "interaction",
        ["current_stage_id", "stage_entered_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_university_id"), "interaction", ["university_id"], unique=False
    )
    op.create_index(
        "uq_interaction_active_triple",
        "interaction",
        ["university_id", "program_id", "product_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'cancelled'"),
    )
    op.create_table(
        "stage_transition_rule",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("from_stage_id", sa.Uuid(), nullable=False),
        sa.Column("to_stage_id", sa.Uuid(), nullable=False),
        sa.Column("requires_comment", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "requires_attachment", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_stage_id"],
            ["stage.id"],
            name=op.f("fk_stage_transition_rule_from_stage_id_stage"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_stage_id"],
            ["stage.id"],
            name=op.f("fk_stage_transition_rule_to_stage_id_stage"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["workflow_version.id"],
            name=op.f("fk_stage_transition_rule_version_id_workflow_version"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_transition_rule")),
        sa.UniqueConstraint(
            "from_stage_id",
            "to_stage_id",
            name=op.f("uq_stage_transition_rule_from_stage_id_to_stage_id"),
        ),
    )
    op.create_index(
        op.f("ix_stage_transition_rule_version_id"),
        "stage_transition_rule",
        ["version_id"],
        unique=False,
    )
    op.create_table(
        "assignment_change",
        sa.Column("interaction_id", sa.Uuid(), nullable=False),
        sa.Column("from_user_id", sa.Uuid(), nullable=True),
        sa.Column("to_user_id", sa.Uuid(), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["app_user.id"],
            name=op.f("fk_assignment_change_changed_by_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["app_user.id"],
            name=op.f("fk_assignment_change_from_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interaction.id"],
            name=op.f("fk_assignment_change_interaction_id_interaction"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"],
            ["app_user.id"],
            name=op.f("fk_assignment_change_to_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignment_change")),
    )
    op.create_index(
        op.f("ix_assignment_change_interaction_id"),
        "assignment_change",
        ["interaction_id"],
        unique=False,
    )
    op.create_table(
        "interaction_contact",
        sa.Column("interaction_id", sa.Uuid(), nullable=False),
        sa.Column("contact_person_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_person_id"],
            ["contact_person.id"],
            name=op.f("fk_interaction_contact_contact_person_id_contact_person"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interaction.id"],
            name=op.f("fk_interaction_contact_interaction_id_interaction"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "interaction_id", "contact_person_id", name=op.f("pk_interaction_contact")
        ),
    )
    op.create_table(
        "interaction_note",
        sa.Column("interaction_id", sa.Uuid(), nullable=False),
        sa.Column("author_user_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["app_user.id"],
            name=op.f("fk_interaction_note_author_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interaction.id"],
            name=op.f("fk_interaction_note_interaction_id_interaction"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interaction_note")),
    )
    op.create_index(
        op.f("ix_interaction_note_interaction_id"),
        "interaction_note",
        ["interaction_id"],
        unique=False,
    )
    op.create_table(
        "radar_signal",
        sa.Column("interaction_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('stage_overdue', 'license_expiring', 'missing_document', 'inactivity')",
            name=op.f("ck_radar_signal_kind"),
        ),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high')", name=op.f("ck_radar_signal_severity")
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interaction.id"],
            name=op.f("fk_radar_signal_interaction_id_interaction"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_radar_signal")),
    )
    op.create_index(
        op.f("ix_radar_signal_interaction_id"), "radar_signal", ["interaction_id"], unique=False
    )
    op.create_index(
        "uq_radar_signal_open",
        "radar_signal",
        ["interaction_id", "kind"],
        unique=True,
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.create_table(
        "transition",
        sa.Column("interaction_id", sa.Uuid(), nullable=False),
        sa.Column("from_stage_id", sa.Uuid(), nullable=True),
        sa.Column("to_stage_id", sa.Uuid(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "source IN ('manual', 'bulk', 'import', 'integration', 'migration')",
            name=op.f("ck_transition_source"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["app_user.id"],
            name=op.f("fk_transition_actor_user_id_app_user"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["from_stage_id"],
            ["stage.id"],
            name=op.f("fk_transition_from_stage_id_stage"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interaction.id"],
            name=op.f("fk_transition_interaction_id_interaction"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_stage_id"],
            ["stage.id"],
            name=op.f("fk_transition_to_stage_id_stage"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transition")),
    )
    op.create_index(
        "ix_transition_interaction_occurred",
        "transition",
        ["interaction_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "attachment",
        sa.Column("interaction_id", sa.Uuid(), nullable=False),
        sa.Column("transition_id", sa.Uuid(), nullable=True),
        sa.Column("stage_id", sa.Uuid(), nullable=False),
        sa.Column("document_type", sa.String(length=60), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interaction.id"],
            name=op.f("fk_attachment_interaction_id_interaction"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stage.id"],
            name=op.f("fk_attachment_stage_id_stage"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transition_id"],
            ["transition.id"],
            name=op.f("fk_attachment_transition_id_transition"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["app_user.id"],
            name=op.f("fk_attachment_uploaded_by_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachment")),
    )
    op.create_index(
        op.f("ix_attachment_interaction_id"), "attachment", ["interaction_id"], unique=False
    )
    # ### end Alembic commands ###

    # История переходов и журнал аудита только дописываются (ADR-005).
    op.execute(
        """
        CREATE FUNCTION forbid_update_delete() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'Таблица % только дописывается', TG_TABLE_NAME
                USING ERRCODE = 'restrict_violation';
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER transition_append_only BEFORE UPDATE OR DELETE ON transition "
        "FOR EACH ROW EXECUTE FUNCTION forbid_update_delete()"
    )
    op.execute(
        "CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON audit_log "
        "FOR EACH ROW EXECUTE FUNCTION forbid_update_delete()"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
    op.execute("DROP TRIGGER IF EXISTS transition_append_only ON transition")
    op.execute("DROP FUNCTION IF EXISTS forbid_update_delete()")
    op.drop_constraint(op.f("fk_team_manager_user_id_app_user"), "team", type_="foreignkey")
    op.drop_index(op.f("ix_attachment_interaction_id"), table_name="attachment")
    op.drop_table("attachment")
    op.drop_index("ix_transition_interaction_occurred", table_name="transition")
    op.drop_table("transition")
    op.drop_index(
        "uq_radar_signal_open",
        table_name="radar_signal",
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    op.drop_index(op.f("ix_radar_signal_interaction_id"), table_name="radar_signal")
    op.drop_table("radar_signal")
    op.drop_index(op.f("ix_interaction_note_interaction_id"), table_name="interaction_note")
    op.drop_table("interaction_note")
    op.drop_table("interaction_contact")
    op.drop_index(op.f("ix_assignment_change_interaction_id"), table_name="assignment_change")
    op.drop_table("assignment_change")
    op.drop_index(op.f("ix_stage_transition_rule_version_id"), table_name="stage_transition_rule")
    op.drop_table("stage_transition_rule")
    op.drop_index(
        "uq_interaction_active_triple",
        table_name="interaction",
        postgresql_where=sa.text("status <> 'cancelled'"),
    )
    op.drop_index(op.f("ix_interaction_university_id"), table_name="interaction")
    op.drop_index("ix_interaction_stage_entered", table_name="interaction")
    op.drop_index(op.f("ix_interaction_program_id"), table_name="interaction")
    op.drop_index(op.f("ix_interaction_product_id"), table_name="interaction")
    op.drop_index("ix_interaction_owner_status", table_name="interaction")
    op.drop_table("interaction")
    op.drop_index(op.f("ix_stage_version_id"), table_name="stage")
    op.drop_table("stage")
    op.drop_table("program_product")
    op.drop_table("product_direction")
    op.drop_index(op.f("ix_workflow_version_template_id"), table_name="workflow_version")
    op.drop_table("workflow_version")
    op.drop_table("stage_norm")
    op.drop_index(op.f("ix_program_direction_id"), table_name="program")
    op.drop_table("program")
    op.drop_index(op.f("ix_product_vendor_id"), table_name="product")
    op.drop_table("product")
    op.drop_index(op.f("ix_contract_university_id"), table_name="contract")
    op.drop_table("contract")
    op.drop_index(op.f("ix_contact_person_university_id"), table_name="contact_person")
    op.drop_table("contact_person")
    op.drop_index(op.f("ix_app_user_team_id"), table_name="app_user")
    op.drop_table("app_user")
    op.drop_table("workflow_template")
    op.drop_table("vendor")
    op.drop_table("university")
    op.drop_table("team")
    op.drop_table("direction")
    op.drop_index(op.f("ix_audit_log_occurred_at"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
