"""report jobs

Revision ID: 5965b66cc7ec
Revises: 8e758533e133
Create Date: 2026-09-16 21:31:49.968591+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5965b66cc7ec"
down_revision: str | Sequence[str] | None = "8e758533e133"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_job",
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("format", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("file_key", sa.String(length=300), nullable=True),
        sa.Column("error_code", sa.String(length=40), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "format IN ('xlsx', 'xls', 'pdf', 'json')", name=op.f("ck_report_job_format")
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'done', 'failed')", name=op.f("ck_report_job_status")
        ),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name=op.f("ck_report_job_progress")),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["app_user.id"],
            name=op.f("fk_report_job_requested_by_app_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_job")),
    )
    op.create_index(
        op.f("ix_report_job_requested_by"), "report_job", ["requested_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_job_requested_by"), table_name="report_job")
    op.drop_table("report_job")
    # ### end Alembic commands ###
