"""norm suggestion percentile

Revision ID: 8e758533e133
Revises: caf77450ee75
Create Date: 2026-09-16 14:35:24.954619+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8e758533e133"
down_revision: str | Sequence[str] | None = "caf77450ee75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stage_norm", sa.Column("suggested_percentile_days", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stage_norm", "suggested_percentile_days")
    # ### end Alembic commands ###
