"""metric source in key

Revision ID: 8fdb850e12c1
Revises: f655a5308c2b
Create Date: 2026-09-16 21:42:58.041590+00:00
"""

from collections.abc import Sequence

from alembic import op

revision: str = "8fdb850e12c1"
down_revision: str | Sequence[str] | None = "f655a5308c2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _refuse_if(count_sql: str, message: str) -> None:
    """Проверка средствами SQL: работает и на живой базе, и в скрипте `alembic ... --sql`.

    `message` содержит `%` — туда подставится найденное число.
    """
    op.execute(
        f"DO $$ DECLARE hits bigint; BEGIN SELECT ({count_sql}) INTO hits; "
        f"IF hits > 0 THEN RAISE EXCEPTION '{message}', hits; END IF; END $$"
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_program_metric_university_id_program_id_period_month_metric"),
        "program_metric",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_program_metric_university_id_program_id_period_month_metric_source"),
        "program_metric",
        ["university_id", "program_id", "period_month", "metric", "source"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # После этой миграции одна метрика за месяц может прийти и из LMS, и руками. Прежний ключ
    # таких пар не допускает: вместо голого UniqueViolation объясняем, что делать.
    _refuse_if(
        "SELECT count(*) FROM (SELECT 1 FROM program_metric "
        "GROUP BY university_id, program_id, period_month, metric HAVING count(*) > 1) AS pairs",
        "Откат невозможен: % метрик пришли из нескольких источников за один месяц. "
        "Оставьте по одному значению и повторите откат.",
    )
    op.drop_constraint(
        op.f("uq_program_metric_university_id_program_id_period_month_metric_source"),
        "program_metric",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_program_metric_university_id_program_id_period_month_metric"),
        "program_metric",
        ["university_id", "program_id", "period_month", "metric"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
