"""program metrics

Revision ID: caf77450ee75
Revises: e483bdb1e4c5
Create Date: 2026-09-16 14:26:07.150746+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "caf77450ee75"
down_revision: str | Sequence[str] | None = "e483bdb1e4c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "program_metric",
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("period_month", sa.Date(), nullable=False),
        sa.Column("metric", sa.String(length=16), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "metric IN ('applications', 'students', 'streams')",
            name=op.f("ck_program_metric_metric"),
        ),
        sa.CheckConstraint(
            "source IN ('lms', 'site', 'manual', 'demo')", name=op.f("ck_program_metric_source")
        ),
        sa.CheckConstraint("value >= 0", name=op.f("ck_program_metric_value_not_negative")),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
            name=op.f("fk_program_metric_program_id_program"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["university.id"],
            name=op.f("fk_program_metric_university_id_university"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_program_metric")),
        sa.UniqueConstraint(
            "university_id",
            "program_id",
            "period_month",
            "metric",
            name=op.f("uq_program_metric_university_id_program_id_period_month_metric"),
        ),
    )
    op.create_index(
        op.f("ix_program_metric_program_id"), "program_metric", ["program_id"], unique=False
    )
    op.create_index(
        op.f("ix_program_metric_university_id"), "program_metric", ["university_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_program_metric_university_id"), table_name="program_metric")
    op.drop_index(op.f("ix_program_metric_program_id"), table_name="program_metric")
    op.drop_table("program_metric")
    # ### end Alembic commands ###
